### ISSUE TITLE
Sort out version handling for h3 lib

### ISSUE THREAD

**Issue by seanhandley** [StuartApp/h3_ruby#16]

**Comment by dfellis** [comment]
Pattern used in other bindings:

* Before feature parity is reached, basic semver in 1.x
* Once feature parity is reached, match the C H3 major and minor, but increment patch independently, where patch can be either bugfixes in the binding or bugfixes from upstream.

That way, the "what features are available" question is answered: "same as H3 X.Y.0" and which "Z" to use remains "highest for a given "X.Y."

**Comment by seanhandley** [comment]
Sounds reasonable 👍
