### ISSUE TITLE
Update the gem in line with h3 3.4.4

### ISSUE THREAD

**Issue by seanhandley** [StuartApp/h3_ruby#53]
https://github.com/uber/h3/releases/tag/v3.4.4

**Comment by seanhandley** [comment]
Actually, it looks like this release has no API changes at all 🤦‍♂

**Comment by dfellis** [comment]
There is one bugfix in that release that affects rendering some hexagons (near the south pole, I think?)

**Comment by seanhandley** [comment]
Thanks @dfellis - that's an easy update then.

**Comment by seanhandley** [comment]
h3 is updated - just need to tag and release to ruby gems.
